config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show edit destroy update]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  get "statistic_pages/policy" => "static_pages#policy", as: :policy
  get "statistic_pages/terms" => "static_pages#terms", as: :terms

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # OGP画像のルーティング
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"
end

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-base-200">
    <div class="flex-1">
      <%= link_to '/' do %>
      <%= image_tag 'yarakashi.png', size: "150x20" %>
      <% end %>
    </div>
    <div class="font-body font-bold tracking-tighter flex-none">
      <ul class="menu menu-horizontal px-1 text-base">
        <li><%= link_to t('header.login'), login_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation" class="alert bg-error text-white my-4">
  <ul class="mb-0">
    <% object.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
<div class="<%= flash_background_color(message_type) %> px-4 py-2 rounded-md text-white mb-4">
  <%= message %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-base-100 w-full">
  <div class="footer footer-center text-base-content p-10">
    <nav class="grid grid-flow-col gap-4 ">
      <a class="link link-hover"><%= link_to "プライバシーポリシー", policy_path, class: "hover:underline", target: :_blank, rel: "noopener noreferrer" %></a>
      <a class="link link-hover"><%= link_to "利用規約", terms_path, class: "hover:underline", target: :_blank, rel: "noopener noreferrer" %></a>
      <a><%= link_to "お問い合わせ", "https://docs.google.com/forms/d/e/1FAIpQLScE5LKGLahySwli5mJQ_lmkX1stS7jUHJaaYMpVUvWrNazmcg/viewform?usp=dialog", class: "hover:underline", target: :_blank, rel: "noopener noreferrer" %></a>
    </nav>
    <nav>
      <div class="grid grid-flow-col gap-4">
        <a href="https://x.com/WebTatsuya0707">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1226" width="24" height="24" class="fill-current w-10">
            <path d="M714.163 519.284L1160.89 0H1055.03L667.137 450.887L357.328 0H0L468.492 681.821L0 1226.37H105.866L515.491 750.218L842.672 1226.37H1200L714.137 519.284H714.163ZM569.165 687.828L521.697 619.934L144.011 79.6944H306.615L611.412 515.685L658.88 583.579L1055.08 1150.3H892.476L569.165 687.854V687.828Z" />
          </svg>
        </a>
        <a href="https://github.com/nakatatsu77">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 496 512">
            <!--!Font Awesome Free 6.7.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
            <path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z" />
          </svg>
        </a>
      </div>
    </nav>
    <aside>
      <div class="font-handwritten">© 2025 - バイトやらかしにっき</div>
    </aside>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-base-200">
    <div class="flex-1">
      <%= link_to '/' do %>
      <%= image_tag 'yarakashi.png', size: "150x20" %>
      <% end %>
    </div>
    <div class="font-body font-bold tracking-tighter flex-none">
      <ul class="menu menu-horizontal px-1 text-base">
        <li><%= link_to t('header.logout'), logout_path, data: { turbo_method: :delete } %></li>
        <li><%= link_to t('header.post_index'), posts_path %></li>
        <li><%= link_to t('header.create_post'), new_post_path %></li>
      </ul>
    </div>
  </div>
</header>