config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show edit destroy update]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  get "statistic_pages/policy" => "static_pages#policy", as: :policy
  get "statistic_pages/terms" => "static_pages#terms", as: :terms

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # OGP画像のルーティング
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  has_one :image, dependent: :destroy
  # app/views/posts/new.html.erbでネストされたフォームを動作させる
  accepts_nested_attributes_for :image, allow_destroy: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # 設定したprepare_meta_tagsをprivateにあってもpostコントローラー以外にも使えるようにする
  helper_method :prepare_meta_tags

  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
    # postモデルに'has_one :image'の関連付けを行っている
    # 関連するImageオブジェクトを作成して@postに関連付ける。
    @post.build_image
  end

  def create
    @post = current_user.posts.build(post_params)
    # 画像生成ロジックをスキップし、通常の投稿を処理
    if @post.image.present? && !params[:generate_image].present?
      @post.image.user = current_user
    end

    # 「画像を生成して投稿する」ボタンが押された場合
    if params[:generate_image].present? && @post.body.present?
      # bodyの内容をプロンプトとして渡す
      generated_image_url = OpenaiImageGenerator.generate_image(@post.body)
      if generated_image_url
        # Postに関連付けられたImageオブジェクトのimage_urlを設定
        @post.build_image(remote_image_url: generated_image_url, is_generated_by_ai: true, user: current_user)
      else
        flash.now[:danger] = "画像生成に失敗しました。もう一度お試しください。"
        render :new and return
      end
    end

    if @post.save
      redirect_to posts_path, success: t("defaults.flash_message.created", item: Post.model_name.human)
    else
      Rails.logger.debug "Post Errors: #{@post.errors.full_messages}"
      flash.now[:danger] = @post.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    # メタタグを設定する。
    prepare_meta_tags(@post)
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), success: t("defaults.flash_message.updated", item: Post.model_name.human)
    else
      flash.now[:danger] = t("defaults.flash_message.not_updated", item: Post.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, status: :see_other, success: t("defaults.flash_message.deleted", item: Post.model_name.human)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, image_attributes: [ :image_url, :image_url_cache, :is_generated_by_ai, :id, :_destroy ]) # image_attributesによってImageモデルのデータを保存、更新できる
  end

  def prepare_meta_tags(post)
        # このimage_urlにMiniMagickで設定したOGPの生成した合成画像を代入する
        image_url = "#{request.base_url}/images/ogp.png?text=#{CGI.escape(post.body)}"
        set_meta_tags og: {
                        site_name: "バイトやらかしにっき",
                        title: post.body,
                        description: "職場でのやらかしエピソードの投稿です",
                        type: "website",
                        url: request.original_url,
                        image: image_url,
                        locale: "ja-JP"
                      },
                      twitter: {
                        card: "summary_large_image",
                        site: "@https://x.com/WebTatsuya0707",
                        image: image_url
                      }
      end
end

app/views/posts/_post.html.erb
<div class="mb-3">
  <div id="post-id-<%= post.id %>">
    <div class="book" data-username="<%= post.user.name %>">
      <%= link_to(post_path(post)) do %>
      <div class="book-inbox">
        <h4 class="card-title flex-col w-full h-28 mb-3 bg-cover">
          <% if post.image&.image_url.present? %>
          <%= image_tag post.image.image_url.url, class: "w-full h-full object-cover" %>
          <% else %>
          <%= image_tag "post_placeholder.png", class: "w-full h-full object-cover"%>
          <% end %>
        </h4>
        <div class="vertical-rl overflow-hidden  w-full text-xs">
          <ul class="max-h-[100px] overflow-hidden break-words p-1">
            <li><%= post.body %></li>
            <li class="text-end pr-2"><%= post.user.name %></li>
          </ul>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<section class="mx-4 my-4">
  <div class="text-3xl mb-4">
    <h1 class="font-handwritten"><%= t('.title') %></h1>
  </div>
  <div class="border-2 border-neutral mx-auto max-w-5xl bg-neutral-content">
    <div class="mx-8 my-8">
      <%= form_with model: @post, local: true, html: { multipart: true } do |f| %>
      <div class="mb-8 w-auto h-96 border-2">
        <%= f.fields_for :image do |image_fields| %>
        <%= image_fields.file_field :image_url, class: "form-control", accept: "image/*" %>
        <% end %>
      </div>
      <div class="mb-3">
        <%= f.text_area :body, class: "vertical-rl resize-none focus:outline-none text-2xl tracking-widest px-3 overflow-hidden w-full h-96 break-all overflow-scroll", placeholder:"やらかしエピソード" %>
      </div>
      <%= f.submit "更新", class: "btn btn-primary text-white" %>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<div class="mx-4 my-4 flex-grow">
  <div class="container relative m-auto">
    <h1 class="font-handwritten text-3xl text-center"><%= t('.title') %></h1>
    <%
=begin%>
    <button class="btn btn-primary text-white"><%= link_to 'みんなのにっき', "#" %></button>
    <%
=end%>
  </div>
  <div class="my-12 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-20">
    <% if @posts.present? %>
    <%= render @posts %>
    <% else %>
    <div class="mb-3">掲示板がありません</div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<section class="mx-4 my-4">
  <div class="text-3xl mb-4">
    <h1 class="font-handwritten"><%= t('.title') %></h1>
  </div>
  <div class="border-2 border-neutral mx-auto max-w-5xl bg-neutral-content">
    <div class="mx-8 my-8">
      <%= form_with model: @post, local: true, html: { multipart: true } do |f| %>
      <div class="mb-8 w-auto h-96 border-2">
        <%= f.fields_for :image do |image_fields| %>
        <%= image_fields.file_field :image_url, class: "form-control", accept: "image/*" %>
        <% end %>
      </div>
      <div class="mb-3">
        <%= f.text_area :body, class: "vertical-rl resize-none focus:outline-none text-2xl tracking-widest px-3 overflow-hidden w-full h-72 break-all overflow-scroll", placeholder:"やらかしエピソード" %>
      </div>
      <%= f.submit "投稿する", class: "btn btn-primary text-white" %>
      <%= button_tag "画像生成して投稿する", name: "generate_image", value: "true", class: "btn btn-secondary text-white" %>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="mx-4 my-4">
  <div class="text-3xl mb-4">
    <h1 class="font-handwritten"><%= t('.title') %></h1>
  </div>
  <div class="border-2 border-neutral mx-auto max-w-5xl bg-neutral-content">
    <div class="mx-8 my-8">
      <div class="mb-8 w-full h-auto border-2">
        <% if @post.image&.image_url.present? %>
        <%= image_tag @post.image.image_url.url, class: "w-full h-auto object-cover" %>
        <% else %>
        <%= image_tag "post_placeholder.png", class: "w-full h-full object-cover"%>
        <% end %>
      </div>
      <ul class="vertical-rl resize-none text-2xl tracking-widest px-3 w-full h-96 break-all overflow-scroll">
        <li><%= @post.body %></li>
        <li class="text-end pr-8"><%= @post.user.name %></li>
      </ul>
      <% if current_user.own?(@post) %>
      <div class='ms-auto flex space-x-1 > *'>
        <%= link_to edit_post_path(@post), id: "button-edit-#{@post.id}" do %>
        <i class="btn">編集</i>
        <% end %>
        <%= link_to post_path(@post), id: "button-delete-#{@post.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') } do %>
        <i class="btn">削除</i>
        <% end %>
        <% prepare_meta_tags @post %>
        <% twitter_share_url = "https://twitter.com/share?url= #{CGI.escape(post_url(@post))}" %>
        <%= link_to twitter_share_url, class: "btn text-xl flex",target: '_blank', data: { toggle: "tooltip", placement: "bottom" }, title: "Xでシェア" do %>
        <svg width="18" viewBox="0 0 30 31" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M25.6228 3.54931C26.0098 3.8933 26.0446 4.48587 25.7006 4.87285L17.5519 14.0402L26.0487 24.9644C26.2424 25.2139 26.3627 25.5132 26.395 25.8274C26.4273 26.1416 26.3708 26.4585 26.2319 26.7421C26.093 27.0258 25.8773 27.2647 25.6093 27.4319C25.3414 27.599 25.032 27.6875 24.7162 27.6875C24.7161 27.6875 24.7163 27.6875 24.7162 27.6875H21.6162L21.6148 27.6875C21.358 27.6871 21.1047 27.6282 20.8742 27.5151C20.6437 27.402 20.442 27.2378 20.2845 27.035L13.6187 18.465L5.70065 27.3729C5.35666 27.7598 4.76409 27.7947 4.37711 27.4507C3.99013 27.1067 3.95527 26.5142 4.29926 26.1272L12.448 16.9598L3.95119 6.03559C3.75749 5.78615 3.63722 5.48678 3.60492 5.17261C3.57262 4.85845 3.62912 4.54153 3.76801 4.25789C3.9069 3.97425 4.1226 3.73528 4.39058 3.56815C4.6585 3.40106 4.96794 3.31249 5.2837 3.31251C5.28376 3.31251 5.28365 3.31251 5.2837 3.31251H8.3851C8.64187 3.31289 8.89517 3.37187 9.1257 3.48494C9.35602 3.59791 9.55754 3.7619 9.71496 3.96443C9.71511 3.96462 9.71481 3.96424 9.71496 3.96443L16.3812 12.535L24.2993 3.62717C24.6432 3.24019 25.2358 3.20533 25.6228 3.54931ZM15.1143 13.9602L8.29088 5.18751H5.66695L13.7149 15.5346L15.1143 13.9602ZM14.8856 17.0398L21.709 25.8125H24.333L16.285 15.4654L14.8856 17.0398Z" />
        </svg>
        <p>シェア</p>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</section>