config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#top"
  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show edit destroy update]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  get "statistic_pages/policy" => "static_pages#policy", as: :policy
  get "statistic_pages/terms" => "static_pages#terms", as: :terms

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # OGP画像のルーティング
  get "images/ogp.png", to: "images#ogp", as: "images_ogp"
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to posts_path, success: t("user_sessions.create.success")
    else
      flash.now[:danger] = t("user_sessions.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t("user_sessions.destroy.success")
  end
end

app/views/user_sessions/new.html.erb
<div class='container mx-auto'>
  <div class='text-center mt-6'>
    <h1 class='text-2xl font-handwritten font-lilita'><%= t('.title') %></h1>
  </div>
  <%= form_with url: login_path do |f| %>
  <%
=begin%>
  <%= render 'shared/error_messages', model: f.object %>
  <%
=end%>

  <%= f.label :email, class: 'label w-full md:w-1/2 mx-auto' %>
  <%= f.email_field :email, class: 'input input-bordered border-2 input-accent form-control mb-6 w-full md:w-1/2 mx-auto' %>

  <%= f.label :password, class: 'label w-full md:w-1/2 mx-auto'%>
  <%= f.password_field :password, class: 'input input-bordered border-2 input-accent form-control mb-6 w-full md:w-1/2 mx-auto' %>

  <div class='mx-auto md:w-1/2'>
    <%= f.submit t('.login'), class: 'btn btn-primary text-white w-full mt-6 mb-6 mx-auto' %>
    <%= link_to 'Login with Google', auth_at_provider_path(provider: :google) %>
  </div>
  <% end %>

  <div class='text-center mb-6'>
    <%= link_to t('.to_register_page'), new_user_path %>
    <%= link_to t('.password_forget'), '#' %>
  </div>
</div>